# Generated by Django 5.0.6 on 2024-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
